#!/bin/bash

#
# menubar
chunkc set custom_bar_enabled            1
chunkc set custom_bar_all_monitors       1
chunkc set custom_bar_offset_top         0
chunkc set custom_bar_offset_bottom      0
chunkc set custom_bar_offset_left        0
chunkc set custom_bar_offset_right       0

#
# global
chunkc set global_desktop_mode           bsp
chunkc set global_desktop_offset_top     12
chunkc set global_desktop_offset_bottom  12
chunkc set global_desktop_offset_left    12
chunkc set global_desktop_offset_right   12
chunkc set global_desktop_offset_gap     12
chunkc set desktop_padding_step_size     5.0
chunkc set desktop_gap_step_size         1.0

#
# desktop 1
chunkc set 1_desktop_mode                monocle
chunkc set 1_desktop_offset_top          0
chunkc set 1_desktop_offset_bottom       0
chunkc set 1_desktop_offset_left         0
chunkc set 1_desktop_offset_right        0
chunkc set 1_desktop_offset_gap          0

#
# desktop 2
chunkc set 2_desktop_mode                float

#
# bsp mode
chunkc set bsp_spawn_left                0 
chunkc set bsp_optimal_ratio             1
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.500

#
# etc
chunkc set window_focus_cycle            all
chunkc set window_float_next             0
chunkc set window_float_center           0
chunkc set window_region_locked          0

#
# key binds
chunkc set mouse_move_window \"cmd 1\"
chunkc set mouse_resize_window \"shift 1\"

#
# borders (requires `border.so`)
chunkc set preselect_border_color        0xfff0f0f0
chunkc set preselect_border_width        1
chunkc set preselect_border_radius       5
chunkc set focused_border_color          0xaaffffff
chunkc set focused_border_width          9
chunkc set focused_border_radius         6
chunkc set focused_border_skip_floating  0
chunkc set focused_border_outline        1
chunkc set focused_border_skip_monocle   0

#
# always floating
chunkc tiling::rule --owner Finder --name Copy --state float
chunkc tiling::rule --owner \"App Store\" --state float

#
# set colors from pywal
source ~/.cache/wal/chunkwmcolors
NFOCUS=$(echo $FOCUS | sed 's/#//')
NPRESE=$(echo $PRESE | sed 's/#//')
chunkc set preselect_border_color        $NPRESE
chunkc set focused_border_color          $NFOCUS

#
# load plugins
chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins
chunkc core::load border.so
chunkc core::load tiling.so
#chunkc core::load ffm.so
#chunkc core::load purify.so
chunkc set mouse_follows_focus           on
