#!/usr/bin/env bash
message=install homebrew packages

message=install homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew update
brew upgrade

message=save homebrew’s installed location.

BREW_PREFIX=$(brew --prefix)

message=install gnu core utilities (those that come with macos are outdated).
message=you might have to add this to your path yourself

echo "/usr/bin/local\n${HOME}/scripts/bin\n${HOME}/.bin\n$(brew --prefix coreutils)/libexec/gnubin" > /etc/paths.d/paths

brew install coreutils
ln -s "${BREW_PREFIX}/bin/gsha256sum" "${BREW_PREFIX}/bin/sha256sum"

message=install some other useful utilities like `sponge`.
brew install moreutils

message=install gnu `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
brew install findutils

message=install gnu `sed`, overwriting the built-in `sed`.
brew install gnu-sed

message=install bash 4.
brew install bash
brew install bash-completion2
brew install grep
brew install python3
brew install zsh

message=switch to zsh and bash4
sudo sh -c 'echo /usr/local/bin/zsh >> /etc/shells && chsh -s /usr/local/bin/zsh'
echo "${BREW_PREFIX}/bin/bash" | sudo tee -a /etc/shells
chsh -s "${BREW_PREFIX}/bin/bash"
brew install neovim
brew install tmux
brew install weechat 
#brew install irssi
brew install ncmpcpp
brew install ranger
brew install htop
brew tap cjbassi/gotop
brew install gotop
brew install neofetch
brew install redshift
brew install git
brew install git-lfs
brew install imagemagick
brew install jq
brew install mpd
brew tap mopidy/mopidy
brew install mopidy
brew install mpc
brew install sassc
brew install wget
brew install pidof
brew tap caskroom/fonts
brew cask install font-iosevka
brew cask install font-fira-code

message=chunkwm
brew tap koekeishiya/formulae
brew install chunkwm

message=install from git repo
brew install --HEAD chunkwm

message=skhd
brew install koekeishiya/formulae/skhd

message=mopidy
brew tap mopidy/mopidy
brew install mopidy-scrobbler

message=cask
brew tap caskroom/cask
brew cask install iterm2
brew cask install ubersicht

message=remove outdated versions from the cellar.
brew cleanup
