#!/usr/bin/env bash
# original by mathias, @zzzeyez version


# Install command-line tools using Homebrew.

# Make sure we’re using the latest Homebrew.
brew update

# Upgrade any already-installed formulae.
brew upgrade

# Save Homebrew’s installed location.
BREW_PREFIX=$(brew --prefix)

# Install GNU core utilities (those that come with macOS are outdated).
echo Don’t forget to add '$(brew --prefix coreutils)/libexec/gnubin' to '$PATH'
brew install coreutils
ln -s "${BREW_PREFIX}/bin/gsha256sum" "${BREW_PREFIX}/bin/sha256sum"

# Install some other useful utilities like `sponge`.
brew install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
brew install findutils
# Install GNU `sed`
brew install gnu-sed
# Install Bash 4.
brew install bash
brew install bash-completion2

# Switch to using brew-installed bash as default shell
if ! fgrep -q "${BREW_PREFIX}/bin/bash" /etc/shells; then
  echo "${BREW_PREFIX}/bin/bash" | sudo tee -a /etc/shells;
  chsh -s "${BREW_PREFIX}/bin/bash";
fi;


# my stuff
# brew install neovim
brew tap jason0x43/homebrew-neovim-nightly
brew cask install neovim-nightly
brew install tmux
#brew install weechat 
brew install irssi
brew install ncmpcpp
#brew install ranger
brew install htop
brew tap cjbassi/gotop
brew install gotop
brew install neofetch
brew install fff
brew install redshift
brew install git
brew install git-lfs
brew install youtube-dl
brew install imagemagick
brew install jq
brew install mpd
brew tap mopidy/mopidy
brew install mopidy
brew install mpc
brew install sassc
brew install wget
brew install pidof
brew install fzf
brew install tree
brew install rmtrash

# install node + npm packages
#curl -sL install-node.now.sh/lts | bash
brew install yarn
npm install -g neovim
npm i -g bash-language-server

# python3
brew install python3

# chunkwm
brew tap koekeishiya/formulae
brew install chunkwm --with-purify
brew install --HEAD chunkwm
brew install koekeishiya/formulae/skhd

# mopidy
brew tap mopidy/mopidy
brew install mopidy-scrobbler

# cask
brew tap caskroom/cask
brew cask install the-unarchiver
brew cask install iterm2
brew cask install ubersicht

# remove old versions from cellar
brew cleanup
