#!/usr/bin/env bash
# misc. install commands

# install new-roses
ln -sf "${HOME}/scripts/new-roses/new-roses" "/usr/local/bin/new-roses"

# install colorlovers
ln -sf "${HOME}/scripts/colorlovers/colorlovers" "/usr/local/bin/colorlovers"

# install pecan + xanthia
mkdir -p "Library/Application Support/Übersicht/widgets"
ln -s "${HOME}/scripts/pecan" "${HOME}/Library/Application Support/Übersicht/widgets/pecan"
ln -sf "${HOME}/scripts/pecan/pecan-style" "/usr/local/bin/pecan-style"
ln -s "${HOME}/scripts/xanthia" "${HOME}/Library/Application Support/Übersicht/widgets/xanthia"

# turn on chwmsa
sudo chunkwm --install-sa
pkill Dock

