#!/usr/bin/env bash
# misc. install commands

# install new-roses
ln -sf "${HOME}/scripts/new-roses/new-roses" "/usr/local/bin/new-roses"

# install colorlovers
ln -sf "${HOME}/scripts/colorlovers/colorlovers" "/usr/local/bin/colorlovers"

# install pecan + xanthia
mkdir -p "Library/Application Support/Übersicht/widgets"
ln -s "${HOME}/scripts/pecan" "${HOME}/Library/Application Support/Übersicht/widgets/pecan"
ln -sf "${HOME}/scripts/pecan/pecan-style" "/usr/local/bin/pecan-style"
ln -s "${HOME}/scripts/xanthia" "${HOME}/Library/Application Support/Übersicht/widgets/xanthia"

# ableton and melodyne insist on creating ~/music
ln -s "${HOME}/behaviors/ableton" "${HOME}/music/ableton"
ln -s "${HOME}/behaviors/celemony" "${HOME}/music/celemony"

# kontakt will only search in ~/documents
ln -s "${HOME}/behaviors/packs/glassmarimba" "${HOME}/documents/glassmarimba"
# might as well put reverbs there too ..
ln -s "${HOME}/behaviors/packs/h3000" "${HOME}/documents/h3000"
# and rhodes..
ln -s "${HOME}/behaviors/packs/rhodes" "${HOME}/documents/rhodes"

# turn on chwmsa
sudo chunkwm --install-sa
pkill Dock

# start background services
brew services start skhd
brew services start chunkwm
brew services start mopidy

